// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService owns config.json. It is fully decoupled from other services.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns the current app config, or a zero-value config if none has
 * been saved yet.
 */
export function GetConfig(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(2320765359).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickGamesFolder opens the native folder-selection dialog and returns the
 * chosen path. It does not persist; the frontend calls SetGamesFolder next. An
 * empty string with nil error means the user cancelled.
 */
export function PickGamesFolder(): $CancellablePromise<string> {
    return $Call.ByID(2294021349);
}

/**
 * SetGamesFolder validates that path exists and is a directory, then persists it
 * as the games root and returns the updated config.
 */
export function SetGamesFolder(path: string): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(2763170140, path).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
