// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameService owns games/*.json and covers/. Fully decoupled from other
 * services; the games root is passed in by the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetImageDataURL reads an image file and returns it as a base64 data URL so the
 * webview can display covers/candidates that live outside the web root. Returns
 * "" for an empty path (caller falls back to the default cover).
 */
export function GetImageDataURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(3601790935, path);
}

/**
 * LaunchGame starts the game's executable detached, leaving the launcher open.
 */
export function LaunchGame(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(3121092458, gameID);
}

/**
 * ListGames reads every games/*.json, sorted by name (case-insensitive).
 */
export function ListGames(): $CancellablePromise<$models.Game[]> {
    return $Call.ByID(2522020450).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveGame deletes the game's json and any copied cover. It does not touch the
 * game's own folder on disk.
 */
export function RemoveGame(gameID: string): $CancellablePromise<void> {
    return $Call.ByID(3324516489, gameID);
}

/**
 * Scan walks each immediate subfolder of root. New folders with an executable
 * become games; known games whose folder/exe is gone are reported as Missing.
 * Scan never deletes — the frontend resolves Missing via Keep/Delete.
 */
export function Scan(root: string): $CancellablePromise<$models.ScanResult> {
    return $Call.ByID(88121630, root).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetCover copies the chosen png into covers/{id}.png and updates the game.
 */
export function SetCover(gameID: string, pngPath: string): $CancellablePromise<$models.Game> {
    return $Call.ByID(1556266360, gameID, pngPath).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateGame persists user edits to an existing game (name, exe, cover).
 */
export function UpdateGame(game: $models.Game): $CancellablePromise<$models.Game> {
    return $Call.ByID(2417788572, game).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Game.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ScanResult.createFrom;
