// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

/**
 * AppConfig holds app-level settings persisted to config.json.
 */
export class AppConfig {
    /**
     * GamesFolder is the root folder the user picked; each immediate subfolder
     * is treated as a game.
     */
    "gamesFolder": string;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("gamesFolder" in $$source)) {
            this["gamesFolder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

/**
 * Game is a single launchable fan game. Persisted as games/{id}.json.
 */
export class Game {
    "id": string;

    /**
     * defaults to folder name, editable
     */
    "name": string;

    /**
     * absolute path to the game subfolder
     */
    "folderPath": string;

    /**
     * absolute path to the chosen executable
     */
    "exePath": string;

    /**
     * absolute path to chosen cover, or "" for default
     */
    "coverPath": string;

    /**
     * LastPlayed is when the game was last launched; nil if never played.
     */
    "lastPlayed": time$0.Time | null;

    /**
     * PlaytimeSeconds is the cumulative time the game's process has run, summed
     * across all completed sessions tracked by the launcher.
     */
    "playtimeSeconds": number;

    /** Creates a new Game instance. */
    constructor($$source: Partial<Game> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("folderPath" in $$source)) {
            this["folderPath"] = "";
        }
        if (!("exePath" in $$source)) {
            this["exePath"] = "";
        }
        if (!("coverPath" in $$source)) {
            this["coverPath"] = "";
        }
        if (!("lastPlayed" in $$source)) {
            this["lastPlayed"] = null;
        }
        if (!("playtimeSeconds" in $$source)) {
            this["playtimeSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Game instance from a string or object.
     */
    static createFrom($$source: any = {}): Game {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Game($$parsedSource as Partial<Game>);
    }
}

/**
 * GameCoverOptions lists candidate cover images discovered for a newly added
 * game so the frontend can prompt the user to pick one.
 */
export class GameCoverOptions {
    "gameId": string;
    "name": string;

    /**
     * candidate image paths in the folder
     */
    "images": string[];

    /** Creates a new GameCoverOptions instance. */
    constructor($$source: Partial<GameCoverOptions> = {}) {
        if (!("gameId" in $$source)) {
            this["gameId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("images" in $$source)) {
            this["images"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameCoverOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): GameCoverOptions {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField2_0($$parsedSource["images"]);
        }
        return new GameCoverOptions($$parsedSource as Partial<GameCoverOptions>);
    }
}

/**
 * ScanResult is returned by Scan so the frontend can drive follow-up prompts.
 */
export class ScanResult {
    /**
     * newly discovered games
     */
    "added": Game[];

    /**
     * games with candidate covers
     */
    "needsCoverChoice": GameCoverOptions[];

    /**
     * known games whose folder/exe is gone
     */
    "missing": Game[];

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("added" in $$source)) {
            this["added"] = [];
        }
        if (!("needsCoverChoice" in $$source)) {
            this["needsCoverChoice"] = [];
        }
        if (!("missing" in $$source)) {
            this["missing"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("added" in $$parsedSource) {
            $$parsedSource["added"] = $$createField0_0($$parsedSource["added"]);
        }
        if ("needsCoverChoice" in $$parsedSource) {
            $$parsedSource["needsCoverChoice"] = $$createField1_0($$parsedSource["needsCoverChoice"]);
        }
        if ("missing" in $$parsedSource) {
            $$parsedSource["missing"] = $$createField2_0($$parsedSource["missing"]);
        }
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Game.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = GameCoverOptions.createFrom;
const $$createType4 = $Create.Array($$createType3);
